variables:
  DOCKER_IMAGE: registry.git.rwth-aachen.de/acs/public/villas/controller
stages:
  - build
  - deploy

# Stage: build
##############################################################################

build:docker:
  stage: build
  image: docker
  script:
    - docker build --tag ${DOCKER_IMAGE} .
  tags:
    - docker

build:flake8:
  stage: build
  image: python:3.8
  script:
  - pip3 install flake8
  - flake8 .
  tags:
    - docker

build:dist:
  stage: build
  image: python:3.8
  script:
    - python3 setup.py sdist
  artifacts:
    paths:
      - dist/
  tags:
    - docker

# Stage: deploy
##############################################################################

deploy:docker:
  stage: deploy
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker push ${DOCKER_IMAGE}
  tags:
    - shell
    - linux
  only:
    - ci-docker
