repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args:
    - --autofix
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.22.0
  hooks:
  - id: check-jsonschema
    name: "Check schemas"
    language: python
    files: ^villas/controller/schemas/.*\.yaml$
    types: [yaml]
    args: ["--verbose", "--schemafile", "https://json-schema.org/draft/2020-12/schema"]
  - id: check-jsonschema
    name: "Check OpenAPI doc"
    language: python
    files: ^doc/openapi.yaml$
    types: [yaml]
    args: ["--schemafile", "https://github.com/OAI/OpenAPI-Specification/tree/main/_archive_/schemas/v3.0/schema.yaml"]
