---
broker:
  url: amqp://villas:Haegiethu0rohtee@kubernetes-master-1.os-cloud.eonerc.rwth-aachen.de:30809/%2F

components:
- type: generic
  category: manager
  name: Generic Manager
  location: Steffens Laptop
  uuid: eddb51a0-557b-4848-ac7a-faa3e7c51fa3

- category: manager
  type: kubernetes

  name: Kubernetes Manager
  location: Steffens Laptop
  uuid: 4f8fb73e-7e74-11eb-8f63-f3a5b3ab82f6

  namespace: villas-controller
