---
broker:
  url: amqp://villas:Haegiethu0rohtee@k8s.eonerc.rwth-aachen.de:30809/%2F

components:
- api_url: https://villas.k8s.eonerc.rwth-aachen.de/ws/
  category: manager
  type: villas-node
  config: {}
  config_filename: "/Users/stv0g/workspace/rwth/acs/public/villas/node/build_devel_osx/file-playback.conf"
  enabled: true
  executable: "/Users/stv0g/workspace/rwth/acs/public/villas/node/build_devel_osx/src/villas-node"
  location: Steffen's Laptop
  name: VILLASnode (k8s)
  owner: svg
  realm: de.rwth-aachen.eonerc.acs

- api_url: https://villas.k8s.eonerc.rwth-aachen.de/ws/relay
  category: manager
  type: villas-relay
  enabled: true
  location: k8s
  name: VILLASrelay (k8s)
  owner: svg
  realm: de.rwth-aachen.eonerc.acs
